import { useEffect, useState } from "react";
import Head from "next/head";
import { withAuthSync } from "../utils/auth";
import fetch from "isomorphic-unfetch";
import nextCookie from "next-cookies";
import Router from "next/router";
import Layout from "../components/Layout";
import { observer } from "mobx-react-lite";
import cookie from "js-cookie";
import store from "../store/store";

const Accounts = observer(({ id, token, adminId, name }) => {
	const [users, setUsers] = useState([]);

	const connectHandler = (user) => {
		cookie.set("id", user.id, { expires: 1 });
		cookie.set("name", user.name, { expires: 1 });
		Router.push("/");
	};

	useEffect(() => {
		var myHeaders = new Headers();
		myHeaders.append("Authorization", `Bearer ${token}`);

		var requestOptions = {
			method: "GET",
			headers: myHeaders,
			redirect: "follow",
		};

		fetch(
			"https://mediabit.ro/booking/wp-json/wp/v2/users?per_page=100",
			requestOptions
		)
			.then((response) => response.json())
			.then((result) => {
				console.log("res", result);
				setUsers(result);
			})
			.catch((error) => {
				console.log("error", error);
			});
	}, []);

	return (
		<Layout adminId={adminId} name={name}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='rez-list'>
				<h3 className='mb-4'>Users</h3>
				<table className='table table-bordered'>
					<tbody>
						{users.map((user) => (
							<tr key={Math.random()}>
								<td>{user.name}</td>
								<td>
									<button
										onClick={() => connectHandler(user)}
										className='btn btn-primary'>
										Connect
									</button>
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>
		</Layout>
	);
});

Accounts.getInitialProps = (ctx) => {
	const { token, id, adminId } = nextCookie(ctx);

	if (!token || !id) Router.push("/login");

	return {
		token,
		id,
		adminId,
	};
};

export default withAuthSync(Accounts);
