import { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import { withAuthSync } from "../utils/auth";
import fetch from "isomorphic-unfetch";
import nextCookie from "next-cookies";
import Router from "next/router";
import Layout from "../components/Layout";
import Provider from "../components/Provider";
import store from "../store/store";
import { observer } from "mobx-react-lite";
import { toJS } from "mobx";

const Home = observer((props) => {
	console.log("Home props", props);

	const [adminId, setAdminId] = useState(0);
	const [name, setName] = useState(0);

	console.log("name,id", name, adminId);

	useEffect(() => {
		const categories = Object.values(props);
		setAdminId(categories.pop());
		categories.pop();
		setName(categories.pop());
		categories.pop();

		store.locations = categories.filter((item) => item.parent === 0);

		store.providers = categories.filter((item) => item.parent !== 0);
	}, []);

	console.log("providers", toJS(store.locations));

	return (
		<Layout adminId={adminId} name={name}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='row'>
				{store.locations
					.filter((location) =>
						store.providers.find((provider) => provider.parent === location.id)
					)
					.map((location) => (
						<div
							key={"dlc" + location.id}
							style={{ maxWidth: "600px" }}
							className='col-lg-6 mb-3'>
							<div className='p-lg-4 p-3 rounded bg-white'>
								<h5>{location.description}</h5>
								<div className='row'>
									{store.providers
										.filter((provider) => provider.parent === location.id)
										.map((provider) => (
											<div
												key={"plc" + provider.id + "dlc" + location.id}
												className='col-6 col-md-4 mb-3'>
												<Provider data={provider} />
											</div>
										))}
								</div>
								<Link href='/calendar'>
									<a className='btn btn-primary'>Vezi calendar</a>
								</Link>
							</div>
						</div>
					))}
			</div>
		</Layout>
	);
});
Home.getInitialProps = (ctx) => {
	const { token } = nextCookie(ctx);

	var myHeaders = new Headers();
	myHeaders.append("Authorization", `Bearer ${token}`);

	var requestOptions = {
		method: "GET",
		headers: myHeaders,
		redirect: "follow",
	};

	return fetch(
		"https://mediabit.ro/booking/wp-json/wp/v2/categories?acf_format=standard&per_page=100&orderby=slug",
		requestOptions
	)
		.then((response) => response.json())
		.then((result) => {
			console.log("res", result);
			return result;
		})
		.catch((error) => {
			console.log("error", error);
		});
};

export default withAuthSync(Home);
